name: Check Has Changelog Version Matching Semver Label

on:
  workflow_call:
    inputs:
      changelog-file:
        description: The changelog file path.
        required: false
        type: string
      label:
        description: The semver label that indicates which release version will be produced.
        required: true
        type: string
      package-file:
        description: The file where the current version of the package will be found.
        required: false
        type: string
      package-type:
        description: The type of package to check.
        required: true
        type: string

permissions:
  contents: read
  pull-requests: write

env:
  status-report-action-repository: infrastructure-blocks/check-has-changelog-version-matching-semver-label-workflow

jobs:
  check-has-changelog-version-matching-label:
    runs-on: ubuntu-22.04
    steps:
      - id: parse-inputs
        run: |
          if test "${{ runner.debug }}" = "1"; then
            set -x
          fi
      - uses: infrastructure-blocks/status-report-action@v1
        with:
          mode: clear
      - if: ${{ steps.parse-inputs.outputs.skip != 'true' }}
        uses: actions/checkout@v4
      - if: ${{ steps.parse-inputs.outputs.skip != 'true' }}
        id: current-version
        uses: infrastructure-blocks/package-version-action@v1
        with:
          type: ${{ inputs.package-type }}
          file: ${{ inputs.package-file }}
      - if: ${{ steps.parse-inputs.outputs.skip != 'true' }}
        id: next-version
        uses: docker://public.ecr.aws/infrastructure-blocks/semver-increment-action:v1
        with:
          version: ${{ steps.current-version.outputs.version }}
          type: ${{ inputs.label }}
      - if: ${{ steps.parse-inputs.outputs.skip != 'true' }}
        id: check-changelog
        uses: infrastructure-blocks/check-has-changelog-version-action@v1
        with:
          changelog-file: ${{ inputs.changelog-file }}
          version: ${{ steps.next-version.outputs.version }}
      - if: ${{ failure() }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          body: |
            :boom: **Error**: expecting a changelog entry for version `${{ steps.next-version.outputs.version }}` in `${{ steps.check-changelog.outputs.changelog-file }}`!!!
