name: Check Has Changelog Version Matching Semver Increment

on:
  workflow_call:
    inputs:
      changelog-file:
        description: The changelog file path.
        required: false
        type: string
      semver-increment:
        description: The semver increment that indicates which release version will be produced.
        required: true
        type: string
      package-file:
        description: The file where the current version of the package will be found.
        required: false
        type: string
      package-type:
        description: The type of package to check.
        required: true
        type: string
      skip:
        type: boolean
        description: Whether to skip the workflow or not.
        required: false
        default: false

permissions:
  contents: read
  pull-requests: write

env:
  status-report-action-repository: infrastructure-blocks/check-has-changelog-version-matching-semver-semver-increment-workflow

jobs:
<<<<<<< HEAD
  check-has-changelog-version-matching-semver-increment:
=======
  example-job:
>>>>>>> template/master
    runs-on: ubuntu-22.04
    steps:
<<<<<<< HEAD
      # We still clear out the report just in case the previous run had skip set to false.
      - uses: infrastructure-blocks/status-report-action@v1
        with:
          mode: clear
      - if: ${{ !inputs.skip }}
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ inputs.package-type != 'git' && 1 || 0 }}
      - if: ${{ !inputs.skip }}
        id: current-version
        uses: infrastructure-blocks/package-version-action@v1
        with:
          type: ${{ inputs.package-type }}
          file: ${{ inputs.package-file }}
      - if: ${{ !inputs.skip }}
        id: next-version
        uses: docker://public.ecr.aws/infrastructure-blocks/semver-increment-action:v1
        with:
          version: ${{ steps.current-version.outputs.version }}
          type: ${{ inputs.semver-increment }}
      - if: ${{ !inputs.skip }}
        id: check-changelog
        uses: infrastructure-blocks/check-has-changelog-version-action@v1
        with:
          changelog-file: ${{ inputs.changelog-file }}
          version: ${{ steps.next-version.outputs.version }}
      - if: ${{ failure() }}
        uses: infrastructure-blocks/status-report-action@v1
        with:
          body: |
            :boom: **Error**: expecting a changelog entry for version `${{ steps.next-version.outputs.version }}` in `${{ steps.check-changelog.outputs.changelog-file }}`!!!
=======
      # This condition should be on every step.
      - if: ${{ !inputs.skip }}
        id: example-step
        name: Example step
        env:
          BIG_SECRET: ${{ secrets.example-secret }}
        run: |
          echo "your input: ${{ inputs.example-input }}"
          echo "example-output=toto" >> "${GITHUB_OUTPUT}"
>>>>>>> template/master
